### ISSUE TITLE
yath warns of "Filehandle STDOUT reopened as $fh only for input"

### ISSUE THREAD

**Issue by djerius** [Test-More/Test2-Harness#55] opened 2018-03-21 21:30 UTC
```
% yath test --version

Yath version: 0.001062

Other version info:
+----------------+----------+
| COMPONENT      | VERSION  |
+----------------+----------+
| perl           | v5.22.1  |
| App::Yath      | 0.001062 |
| Test2::Harness | 0.001062 |
| Test2::Suite   | 0.000111 |
| Test2::API     | 1.302133 |
| Test::Builder  | 1.302133 |
+----------------+----------+
```
With the following code:

```
use Test2::V0;

{
    package Foo;

    sub new { bless { fh => \*STDOUT }, shift() }
    sub DESTROY { shift->{fh}->close }
}

ok( Foo->new );
done_testing;
```
`yath` gives the following warning:

```
% yath test tst.t
( STDERR )  job  1    ----- START -----
Filehandle STDOUT reopened as $fh only for input at /proj/axaf/ots/pkgs/perl-5.22/x86_64-linux_debian-9/lib/site_perl/5.22.1/Test2/Harness/Util.pm line 70.
( STDERR )  job  1    ------ END ------
( PASSED )  job  1    tst.t

================================================================================

Run ID: D88D9ED6-2D4E-11E8-A18B-6E1FDEDFE4DF

All tests were successful!


0.13295s on wallclock (0.37 usr 0.06 sys + 0.50 cusr 0.09 csys = 1.02 CPU)


```

**Comment by exodist** [comment] 2020-02-07 23:03
Oy.

Well, on the good side this is fixed in major_refactor.. mostly
If yath uses Test::Plugin::MemInfo (defaults to using it) then that plugin throws a similar warning.

I think the problem is that 'fh' must be special/cross package? I do not know. I am not considering this a yath/test2 error. The problem is that if a test is written this way it will interfere with any code that uses `$fh` as a filehandle, even when using it as a lexical one (yikes)

This may actually be a perl bug that needs reporting....

```
use strict;
use warnings;

{
    package Foo;

    sub new { bless { fh => \*STDOUT }, shift() }
    sub DESTROY { shift->{fh}->close }
}

Foo->new;
open(my $fh, '<', __FILE__) or die $!; 
```
result:
```
perl xxx.t
Filehandle STDOUT reopened as $fh only for input at xxx.t line 12.
```

**Comment by exodist** [comment] 2020-02-07 23:06
Not a yath bug.

**Closed by exodist** 2020-02-07 23:06 UTC

**Comment by exodist** [comment] 2020-02-08 04:26
when I brought this to p5p they pointed me at this: https://github.com/Perl/perl5/issues/3905  so not a yath bug, a perl bug, and VERY old one.
